import {
  faLightbulb,
  faBell,
  faEdit,
  faTrashAlt,
  faImage,
  faSquareCheck,
  faWindowRestore,
} from "@fortawesome/free-regular-svg-icons";

import {
  faArchive,
  faBars,
  faSearch,
  faRotateRight,
  faTableCellsLarge,
  faGear,
  faTableCells,
  faXmark,
  faPaintBrush,
  faPlus,
  faCheck,
  faTags,
  faPalette,
  faEllipsisVertical,
  faBoxArchive,
  faFont,
  faBold,
  faItalic,
  faUnderline,
  faHeading,
  faEraser,
  faShareNodes,
  faCrown,
  faExclamationTriangle,
  faUserPlus,
  faPaperPlane,
} from "@fortawesome/free-solid-svg-icons";

export const iconMap = {
  // Sidebar & Modal Icons
  lightbulb: faLightbulb,
  notification: faBell,
  pen: faEdit,
  archive: faArchive,
  trash: faTrashAlt,
  label: faTags,
  plus: faPlus,
  check: faCheck,
  close: faXmark,
  apps: faWindowRestore,

  menu: faBars,
  search: faSearch,
  refresh: faRotateRight,
  viewGrid: faTableCellsLarge,
  viewList: faTableCells,
  settings: faGear,
  list: faSquareCheck,
  paintbrush: faPaintBrush,
  picture: faImage,

  // Note card button icons
  palette: faPalette,
  storage: faBoxArchive,
  ellipsis_vertical: faEllipsisVertical,
  font: faFont,

  // Text formatting icons
  heading1: faHeading,
  heading2: faHeading,
  text: faFont,
  bold: faBold,
  italic: faItalic,
  underline: faUnderline,
  clearFormat: faEraser,
  share: faShareNodes,
  crown: faCrown,
  warning: faExclamationTriangle,
  userPlus: faUserPlus,
  send: faPaperPlane,
};
